user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

upstream learning_processor {
    server 127.0.0.1:8028;
}

upstream course_configurer {
    server 127.0.0.1:8082;
}

upstream auth_server {
	server 127.0.0.1:8090;
}

upstream secure-file-server {
	server 127.0.0.1:8026;
}

server {
       listen 443 ssl;
       server_name app-rnd01.therapbd.net;

       ssl_certificate /usr/local/cert/star_therapdev_net_with_chain.crt;
       ssl_certificate_key /usr/local/cert/star_therapdev_net.key;

       ssl_session_cache  builtin:1000  shared:SSL:10m;
       ssl_protocols  TLSv1 TLSv1.1 TLSv1.2;
       ssl_ciphers HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4;
       ssl_prefer_server_ciphers on;

    location /auth/ {
        proxy_pass http://auth_server;
	    proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Authorization $http_authorization;
        proxy_ssl_verify off;
    }

    location /keys {
        proxy_pass http://localhost:8091;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_ssl_verify off;
    }

    location /api/secure-file-server/ {
        proxy_pass http://secure-file-server;
        proxy_set_header Host $host;
	proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Authorization $http_authorization;
	proxy_ssl_verify off;
    }

    location /jenkins {
	proxy_pass http://localhost:8075/jenkins;
    }

    location /kafka-ui {
        proxy_pass http://localhost:9090/kafka-ui;
    }

    location /kafka/b1/ {
        proxy_pass https://localhost:9092/;
    }

    location /api/course-configurator/ {
        proxy_pass http://course_configurer;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Authorization $http_authorization;
        proxy_ssl_verify off;
    }

    location /api/learning-processor/ {
        proxy_pass http://learning_processor;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Authorization $http_authorization;
        proxy_ssl_verify off;
    }

    location /management-center/ {
        proxy_pass http://127.0.0.1:8070/management-center/;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /learnhub {
        proxy_pass http://localhost:5173/learnhub;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

}
}