spring.application.name=LearningProcessor

server.address=0.0.0.0
server.port=8028

service.name=learning-processor
service.host=127.0.0.1    # or actual host/IP
registry.url=http://192.168.0.215:8761
#registry.url=http://172.16.2.79:8761

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

spring.datasource.url=jdbc:oracle:thin:@bddb02.therapbd.net:1521/trainee_pdb.bddb02.therapbd.net
spring.datasource.username=trainee6
spring.datasource.password=trainee6
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.idle-timeout=30000

feign.multipart.enabled=true
spring.servlet.multipart.enabled=true

course-configurator.url=http://172.16.2.118:8082
secure-file-server.url=http://172.16.2.79:8026

spring.kafka.bootstrap-servers=broker-1:9092,broker-2:9094,broker-3:9096
kafka.topics.notification=notification-topic
kafka.topics.update-info=update-info-topic
kafka.topics.update-info.grp=update-info-grp

springdoc.swagger-ui.path=/api/learning-processor/swagger-ui
springdoc.api-docs.path=/api/learning-processor/v3/api-docs
springdoc.swagger-ui.urls.primary-name=default
server.forward-headers-strategy=framework
springdoc.swagger-ui.display-request-duration=true