spring.application.name=secureFileServer

server.address=0.0.0.0
server.port=8026

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

server.servlet.context-path=/api/secure-file-server

spring.datasource.url=jdbc:oracle:thin:@bddb02.therapbd.net:1521/trainee_pdb.bddb02.therapbd.net
spring.datasource.username=trainee6
spring.datasource.password=trainee6
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.idle-timeout=30000

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

#storage.upload-dir=/home/app-rnd01/File Storage
storage.upload-dir=/var/lib/secureFileStorage/uploads
storage.max-file-size=25242880
storage.allowed-file-types=image/png,image/jpeg,image/gif,image/webp, \
                           application/pdf,application/zip,application/x-tar,application/x-rar-compressed, \
                           video/mp4,video/x-msvideo,video/x-matroska, \
                           text/plain,text/x-c,text/x-c++,text/x-java-source,text/x-python, \
                           application/x-python-code,application/javascript,text/javascript

storage.enable-virus-scan=true
clamav.host=https://app-rnd01.therapdev.net/clamav
clamav.port=443

cors.allowed-origins=http://192.168.0.215:8026

file.hmac.secret=sfdsatw13r3rafasd35r23dhmkhgfi34

springdoc.swagger-ui.path=/swagger-ui
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.urls.primary-name=default
server.forward-headers-strategy=framework

springdoc.swagger-ui.display-request-duration=true