version: '3'

services:
  hazelcast-node-1:
    build: .
    image: anonto355/hazelcast-server:latest
    ports:
      - "5701:5701"
    environment:
      - HZ_PORT=5701

  hazelcast-node-2:
    build: .
    image: anonto355/hazelcast-server:latest
    ports:
      - "5702:5701"
    environment:
      - HZ_PORT=5701

  hazelcast-node-3:
    build: .
    image: anonto355/hazelcast-server:latest
    ports:
      - "5703:5701"
    environment:
      - HZ_PORT=5701
