# Telegraf Output Plugin (Prometheus Client)
[[outputs.prometheus_client]]
  listen = ":9273"  # Telegraf listens on port 9273 for Prometheus scraping
  metric_version = 2

# Docker Input Plugin (Collecting Docker Metrics)
[[inputs.docker]]
  endpoint = "unix:///var/run/docker.sock"  # Docker socket to collect container metrics

# Prometheus Output Plugin - sending metrics to Prometheus
[[outputs.prometheus]]
  # Configure Prometheus as the remote_write endpoint to send data to Prometheus
  url = "http://prometheus:9090/api/v1/write"  # Make sure to use the correct Prometheus URL
  interval = "5s"
  hostname = "learnhub"
