spring.application.name=EmployeeManagement
server.port=8080

spring.datasource.url=jdbc:oracle:thin:@bddb02.therapbd.net:1521/trainee_pdb.bddb02.therapbd.net
spring.datasource.username=trainee2
spring.datasource.password=trainee2
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.security.user.name=
spring.security.user.password=
logging.level.org.springframework.security=DEBUG
#jwt.secret=my_jwt_secret_key
#jwt.expiration=3600000

# Optional
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka
#eureka.client.register-with-eureka=false
#eureka.client.fetch-registry=false