-- DROP SEQUENCES
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE avi_student_seq';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE avi_course_enrollment_seq';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE avi_student_content_seq';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE avi_student_submission_seq';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- DROP TABLES (with CASCADE to handle dependencies)
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE avi_student_submission CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE avi_student_content CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE avi_course_enrollment CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE avi_student CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/