spring.application.name=app

# --------- server -------
server.port=8082

# -------- Spring Doc ----------
springdoc.swagger-ui.display-request-duration=true
server.forward-headers-strategy=framework
springdoc.swagger-ui.path=/swagger-ui
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.urls.primary-name=default

# --- Database Configuration (for Oracle) ---
spring.datasource.url=jdbc:oracle:thin:@bddb02.therapbd.net:1521/trainee_pdb.bddb02.therapbd.net
spring.datasource.username=trainee9
spring.datasource.password=trainee9
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# --- JPA/Hibernate Configuration ---
spring.jpa.hibernate.ddl-auto=none

# Show SQL queries in console (useful for development)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# context path
server.servlet.context-path=/api/course-configurator

# Oracle dialect for Hibernate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

management.endpoints.web.exposure.include=health,info

info.app.name=Spring Boot App
info.app.description=kisher description?

custom.property.1=hello

# Spring Security In-Memory User Configuration
spring.security.user.roles=ADMIN,INSTRUCTOR,STUDENT

# Kafka Configuration
spring.kafka.bootstrap-servers=broker-1:9092,broker-2:9094,broker-3:9096
spring.kafka.client-id=course-configurator
kafka.topics.notification=notification-topic
kafka.topics.notification.grp=notification-grp
kafka.topics.update-info.partition=10
kafka.topics.update-info.replication=3
kafka.topics.update-info=update-info-topic


# Other services
enrollment.client.name=learning-processor
enrollment.client.url=http://172.16.2.79:8028/api/student-course

service.name=course-configurator
service.host=127.0.0.1
registry.url=http://192.168.0.215:8761