spring.application.name=Authentication Token's Public Key Provider
server.address=127.0.0.1
server.port=8091

spring.datasource.url=jdbc:oracle:thin:@bddb02.therapbd.net:1521/trainee_pdb.bddb02.therapbd.net
spring.datasource.username=trainee2
spring.datasource.password=trainee2
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.datasource.hikari.auto-commit=false
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=100
spring.datasource.hikari.connection-timeout=30000

server.forward-headers-strategy=framework